# OpenAI API key
OPENAI_API_KEY = "sk-..."

# Qdrant configuration
QDRANT_API_KEY = "your-qdrant-api-key"
QDRANT_CLUSTER_URL = "https://your-cluster-id.us-east4-0.gcp.cloud.qdrant.io:6333"

# Other app settings (if used)
COLLECTION_NAME = "rfp_responses"
REVIEW_SCORE_THRESHOLD = 0.75
OUTPUT_DIR = "output"
